import { useEffect, useState } from 'react';
import { Button, Input, Label, Table, TableBody, TableCell, TableHeader, TableHeaderCell, TableRow, Textarea, Badge, Checkbox } from '@fluentui/react-components';
import { ArrowDownload20Regular, Copy20Regular } from '@fluentui/react-icons';
import { apiFetch } from '../utils/api';
import { save } from '@tauri-apps/plugin-dialog';
import { writeTextFile } from '@tauri-apps/plugin-fs';

export const NodeCommandRunner = ({ context }: { context: string }) => {
  const [command, setCommand] = useState('uname -a'); const [timeout, setTimeoutValue] = useState('45'); const [running, setRunning] = useState(false); const [results, setResults] = useState<any[]>([]); const [nodes, setNodes] = useState<any[]>([]); const [selectedNodes, setSelectedNodes] = useState<string[]>([]); const [selector, setSelector] = useState('');
  useEffect(() => { apiFetch<{ items: any[] }>(`/api/resources/${context}/nodes`).then(data => setNodes(data.items)).catch(() => setNodes([])); }, [context]);
  const run = async () => { setRunning(true); setResults([]); try { const response = await apiFetch<{ results: any[] }>(`/api/commands/${context}/nodes`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ command, timeout_seconds: Math.min(300, Math.max(5, Number(timeout) || 45)), node_names: selectedNodes, node_selector: selector }) }); setResults(response.results); } finally { setRunning(false); } };
  const csv = () => ['node,status,output', ...results.map(row => [row.node, row.status, row.output].map(value => `"${String(value ?? '').replaceAll('"', '""')}"`).join(','))].join('\n');
  const download = async () => { const path = await save({ defaultPath: 'k8sune-node-command.csv', filters: [{ name: 'CSV', extensions: ['csv'] }] }); if (path) await writeTextFile(path, csv()); };
  return <div style={{ height: '100%', padding: '56px 28px 28px', background: 'var(--bg)', color: 'var(--text-h)', display: 'flex', flexDirection: 'column', gap: '16px', boxSizing: 'border-box' }}><h2 style={{ margin: 0 }}>Run command on nodes</h2><Textarea value={command} onChange={(_, data) => setCommand(data.value)} style={{ minHeight: '96px', fontFamily: 'var(--mono)' }} /><div style={{ display: 'grid', gridTemplateColumns: '1fr 180px', gap: '12px' }}><div><Label>Node label selector</Label><Input placeholder="kubernetes.io/os=linux" value={selector} onChange={(_, data) => setSelector(data.value)} /></div><div><Label>Timeout (seconds)</Label><Input type="number" value={timeout} onChange={(_, data) => setTimeoutValue(data.value)} /></div></div><div style={{ border: '1px solid var(--border)', borderRadius: '10px', padding: '10px', maxHeight: '140px', overflowY: 'auto' }}><Label>Select individual nodes <span style={{ opacity: .6 }}>(empty = all matching nodes)</span></Label><div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px', marginTop: '8px' }}>{nodes.map(node => <Checkbox key={node.name} label={node.name} checked={selectedNodes.includes(node.name)} onChange={(_, data) => setSelectedNodes(data.checked ? [...selectedNodes, node.name] : selectedNodes.filter(name => name !== node.name))} />)}</div></div><div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}><Button appearance="primary" onClick={run} disabled={running || !command.trim()}>{running ? 'Running…' : 'Run command'}</Button>{results.length > 0 && <><Button icon={<Copy20Regular />} onClick={() => navigator.clipboard.writeText(csv())}>Copy CSV</Button><Button icon={<ArrowDownload20Regular />} onClick={download}>Download CSV</Button></>}</div><div style={{ flex: 1, overflow: 'auto', border: '1px solid var(--border)', borderRadius: '10px' }}><Table><TableHeader><TableRow><TableHeaderCell>Node</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell><TableHeaderCell>Output</TableHeaderCell></TableRow></TableHeader><TableBody>{results.map(row => <TableRow key={row.node}><TableCell>{row.node}</TableCell><TableCell><Badge color={row.status === 'Succeeded' ? 'success' : 'important'}>{row.status}</Badge></TableCell><TableCell><code style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{row.output}</code></TableCell></TableRow>)}</TableBody></Table>{!results.length && <div style={{ padding: '3rem', textAlign: 'center', opacity: .5 }}>Run a command to see per-node output.</div>}</div></div>;
};
